const defineAction = ({
  id,
  label,
  intent,
  motion,
  colorway,
  colors,
  intensity,
  duration,
  beats,
}) => Object.freeze({
  id,
  label,
  intent,
  motion,
  colorway,
  colors: Object.freeze(colors),
  intensity,
  duration,
  beats: Object.freeze(beats),
});

export const METABLOOM_ACTIONS = Object.freeze([
  defineAction({
    id: "reform",
    label: "Reform",
    intent: "Return to a calm, singular presence",
    motion: "Gather, soften, and return to rest",
    colorway: "Native Metabloom",
    colors: ["#00eeff", "#ff00ff", "#9d00ff"],
    intensity: 0,
    duration: 980,
    beats: ["Gather", "Soften", "Rest"],
  }),
  defineAction({
    id: "agree",
    label: "Agree",
    intent: "Yes, affirmation, or recognition",
    motion: "A small lift, one clear nod, then a softer nod",
    colorway: "Verdant signal",
    colors: ["#26f7a0", "#00d9ff", "#ffe96a"],
    intensity: 0.46,
    duration: 1540,
    beats: ["Notice", "Nod", "Confirm", "Settle"],
  }),
  defineAction({
    id: "disagree",
    label: "Disagree",
    intent: "No, resistance, or correction",
    motion: "Draws back, gives two deliberate lateral shakes, then holds",
    colorway: "Magenta warning",
    colors: ["#ff315f", "#ff36d1", "#7138ff"],
    intensity: 0.54,
    duration: 1640,
    beats: ["Withdraw", "Shake", "Hold", "Settle"],
  }),
  defineAction({
    id: "happy",
    label: "Happy",
    intent: "Warmth, approval, or welcome",
    motion: "Dips in anticipation, rises into an open welcome, and settles",
    colorway: "Sunlit spectrum",
    colors: ["#ffe36e", "#ff4ecb", "#25ddff"],
    intensity: 0.44,
    duration: 1840,
    beats: ["Gather", "Lift", "Open", "Settle"],
  }),
  defineAction({
    id: "excited",
    label: "Excited",
    intent: "High energy or celebration",
    motion: "Crouches, springs upward, and lands with a smaller rebound",
    colorway: "Electric bloom",
    colors: ["#19f5ff", "#ff2cc3", "#8e3dff"],
    intensity: 0.58,
    duration: 1880,
    beats: ["Crouch", "Spring", "Rebound", "Settle"],
  }),
  defineAction({
    id: "sad",
    label: "Sad",
    intent: "Disappointment, care, or empathy",
    motion: "Hesitates, slowly sinks, and holds a softened silhouette",
    colorway: "Blue hush",
    colors: ["#2456ff", "#7a5cff", "#6edcf5"],
    intensity: 0.48,
    duration: 2320,
    beats: ["Hesitate", "Sink", "Hold", "Recover"],
  }),
  defineAction({
    id: "surprised",
    label: "Surprised",
    intent: "Sudden discovery or alert",
    motion: "Recoils sharply, freezes for a beat, then cautiously returns",
    colorway: "Solar flash",
    colors: ["#fff45a", "#ff7b54", "#23cfff"],
    intensity: 0.52,
    duration: 1580,
    beats: ["Recoil", "Freeze", "Recover", "Settle"],
  }),
  defineAction({
    id: "thinking",
    label: "Thinking",
    intent: "Curiosity or consideration",
    motion: "Tilts away, suspends its motion, and returns thoughtfully",
    colorway: "Violet inquiry",
    colors: ["#7758ff", "#13d8d1", "#c2ff68"],
    intensity: 0.46,
    duration: 2240,
    beats: ["Turn", "Consider", "Hold", "Return"],
  }),
  defineAction({
    id: "sleepy",
    label: "Sleepy",
    intent: "Low energy, rest, or calm",
    motion: "Sinks through a long exhale, briefly rouses, and relaxes",
    colorway: "Moonlit drift",
    colors: ["#3449a8", "#8e87db", "#bdd9ff"],
    intensity: 0.42,
    duration: 2600,
    beats: ["Exhale", "Droop", "Rouse", "Rest"],
  }),
  defineAction({
    id: "angry",
    label: "Angry",
    intent: "Urgency, frustration, or pressure",
    motion: "Draws inward, presses forward twice, and holds its ground",
    colorway: "Ember pressure",
    colors: ["#ff3b30", "#ff8a24", "#5f1d76"],
    intensity: 0.56,
    duration: 1680,
    beats: ["Brace", "Insist", "Hold", "Release"],
  }),
  defineAction({
    id: "curious",
    label: "Curious",
    intent: "Interest, inquiry, or a new question",
    motion: "Edges closer, cocks to one side, and waits attentively",
    colorway: "Violet inquiry",
    colors: ["#7758ff", "#13d8d1", "#c2ff68"],
    intensity: 0.58,
    duration: 2080,
    beats: ["Notice", "Lean in", "Listen", "Return"],
  }),
  defineAction({
    id: "listening",
    label: "Listening",
    intent: "Attention without taking over the conversation",
    motion: "Leans toward you, stills, and makes one tiny acknowledgement",
    colorway: "Quiet tide",
    colors: ["#24d9df", "#719cff", "#b5e8ff"],
    intensity: 0.42,
    duration: 2360,
    beats: ["Approach", "Attend", "Acknowledge", "Return"],
  }),
  defineAction({
    id: "skeptical",
    label: "Skeptical",
    intent: "A considered doubt or a request for evidence",
    motion: "Pulls back, tilts sideways, and holds a questioning posture",
    colorway: "Amber question",
    colors: ["#e9ae48", "#ad78ef", "#58cde2"],
    intensity: 0.55,
    duration: 2180,
    beats: ["Pull back", "Tilt", "Question", "Return"],
  }),
  defineAction({
    id: "relieved",
    label: "Relieved",
    intent: "Tension easing after a difficulty is resolved",
    motion: "Braces briefly, releases through a long exhale, then lifts",
    colorway: "Fresh release",
    colors: ["#60e7bc", "#6fbce8", "#e9d28c"],
    intensity: 0.52,
    duration: 2440,
    beats: ["Brace", "Release", "Exhale", "Lift"],
  }),
  defineAction({
    id: "shy",
    label: "Shy",
    intent: "A modest, bashful response to a personal compliment",
    motion: "Tucks inward, turns aside, and cautiously peeks back",
    colorway: "Rose hush",
    colors: ["#f28cc1", "#b084eb", "#82d9e6"],
    intensity: 0.52,
    duration: 2240,
    beats: ["Tuck", "Turn away", "Peek", "Return"],
  }),
  defineAction({
    id: "resolute",
    label: "Resolute",
    intent: "Clear conviction, a boundary, or a firm recommendation",
    motion: "Gathers, makes one forward commitment, and holds steady",
    colorway: "Steady signal",
    colors: ["#70cfff", "#9575f0", "#f3c86e"],
    intensity: 0.52,
    duration: 1980,
    beats: ["Gather", "Commit", "Hold", "Release"],
  }),
]);

const ACTION_BY_ID = new Map(
  METABLOOM_ACTIONS.map((action) => [action.id, action]),
);

const ACTION_ALIASES = Object.freeze({
  bloom: "surprised",
  companion: "reform",
  drift: "sleepy",
  focus: "thinking",
  grumpy: "angry",
  idle: "reform",
  neutral: "reform",
});

export const METABLOOM_ACTION_IDS = Object.freeze(
  METABLOOM_ACTIONS.map(({ id }) => id),
);

export const resolveMetabloomAction = (value) => {
  if (typeof value !== "string") return null;
  const normalized = value.trim().toLowerCase();
  const actionId = Object.prototype.hasOwnProperty.call(ACTION_ALIASES, normalized)
    ? ACTION_ALIASES[normalized] : normalized;
  return ACTION_BY_ID.get(actionId) || null;
};

export const getDefaultMetabloomAction = () => ACTION_BY_ID.get("reform");
